# -*- coding: UTF-8 -*- 
import csv


A = [
[['LANGUAGE'], ['Language']],
[['CLOTHING'], ['CLOTHING','CLOTHS','COATS']],
[['HEALTH'],['RECOVERY','ADDICTION','AID','AIDS','ALCOHOL','HEALTH','HEALTHCARE','BREAST','HEALTHNET','HEALTHY','HEART','ILL','ILLNESS','IMMUNIZATIONS','CONTRACEPTIVE','XRAY','REPRODUCTIVE','CEREBRAL','SUBSTANCE','SUICIDE PREVENTION','THERAPY','WELLBEING','WELLNESS','VISION','VISUAL','VITAMINS','DENTAL','DENTISTRY','SICK','SMEARS','PRESCRIPTION','PSYCHIATRIC CARE','RECOVERY','REHABILITATION','PHYSCIAL ACTIVITY','PHYSICAL','PHYSICALLY','CRISIS','FITNESS','NAMI','MEDICAID','MEDICAL','MEDICINE','MENTAL','MENTALLY','MERCY','EMERGENCY','EMOTIONAL','EMOTIONALLY','OUTPATIENT','BEHAVIORAL PROBLEMS','ABUSE','ABUSED','EMERGENCIES','EXAMS','EXERCISE','GYNECOLOGY','HOSPITAL','COUNSELING','PAP','PATIENTS','NUTRITION','OBSTETRICAL','EMERGENCY','INJURIES','INJURY','INPATIENT','INTERVENTION','HYGIENE','STD']],
[['HOMELESS'], ['RENTAL','RENTERS','TRANSITIONAL','SHELTER','SHELTERS','RESIDENTIAL','RESIDING','HOMELESS','HOMELESSNESS','HABITAT','FORECLOSURE','HOUSE','HOUSEHOLDS','HOUSING','HOMEOWNERS','HOMES','HUD','MORTGAGE']],
[['LEGAL'], ['ADJUDICATES','COURT','CREDITORS','CARDS','CUSTODY','DELINQUENCY','INVESTIGATIONS','DEATHS','JUVENILE','LAWS']],
[['TRANSPORTATION'],['TRANSPORTATION','TRANSIT','TRAFFIC','CARPOOL','DRIVING','MAP','PARATRANSIT','BUS','COMMUTING']],
[['SPIRITUAL'],['CHURCH','SPIRIT']],
[['EDUCATION'],['EDUCATES','EDUCATION','EDUCATIONAL','TEACHERS','TEACHING','STUDENTS','COLLEGE','LEARN','LEARNING','LESSONS','LIFE SKILLS']],
[['EMPLOYMENT'],['WORK','WORKERS','WORKFORCE','VOCATIONAL PROGRAMS','EMPLOYERS','EMPLOYMENT','JOB','LABOR']],
[['FOOD'],['FOOD','FOODS','STAMPS','BREAKFAST','GARDENTOTABLE','FEED','FEEDING','PERISHABLE','MEAL','MEALS','COOK','NONPERISHABLE','PANTRY','HUNGER','RESTAURANT','LUNCH','KITCHEN']]]




B = [
[["INFANTS"],["NEWBORN","ULTRASOUND","UNBORN","BABIES","BABY","WIC","DIAPER","DIAPERS","PREGNANCY","PREGNANT","PREMATURE","PRENATAL","PEDIATRIC","BIRTH","MATERNITY","LACTATION","EXPECTANT","INFANTS"]],
[["MINORS"],["CHILD","YOUNG","YOUTH","ADOLESCENT","AFTERSCHOOL","DAYCARE","PARENT","PATERNITY","OACAC"]],
[["SENIORS"], ["SENIOR","SENIORS","ELDERLY","OLDER"]],
[["DISABILITY"],["AUTISM","DISABILITIES","DISABILITY","DISABLED","DISORDERS","BLIND","PALSY","EPILEPSY"]],   
[["MALE"],["BOYS"," MEN"]],   
[["FEMALE"],["GIRLS","WOMEN","MOTHERS"]],
[["MULTIPLE"],["FAMILIES","FAMILY","PARENTS"]],
[["LGBT"],["TRANSGENDER","BISEXUAL","GAY","GLBT","LESBIAN", 'LGBT']]]


 

with open('app/tagwork.csv', 'rb') as f:
    csvr = csv.reader(f)
    entries = []
    for i in csvr:
        
        for l in B:
            x = False
            for j in l[1]:
                if (i[1].upper().find(j.upper()) > 0):
                    x = True
                    
            if x:
                entries.append([i[0], l[0][0]])
    
    
    with open('filters.csv','wb') as f:
        csvw = csv.writer(f)

        csvw.writerows(entries)